<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    xmlns:fo="http://www.w3.org/1999/XSL/Format"
    xpath-default-namespace="http://inzeraty.cerm47.cz"
    version="2.0"
    >
    <!-- Root Template -->
    <xsl:template match="/">
        <fo:root>
            <fo:layout-master-set>
                <fo:simple-page-master master-name="A4" page-width="210mm" page-height="297mm" margin="20mm">
                    <fo:region-body/>
                    <fo:region-before extent="15mm"/>
                    <fo:region-after extent="15mm"/>
                </fo:simple-page-master>
            </fo:layout-master-set>
            
            <fo:page-sequence master-reference="A4">
                <fo:static-content flow-name="xsl-region-before">
                    <fo:block text-align="center" font-size="14pt" font-weight="bold">Inzeráty</fo:block>
                </fo:static-content>
                
                <fo:static-content flow-name="xsl-region-after">
                    <fo:block text-align="center" font-size="10pt">Generated by XSLT</fo:block>
                </fo:static-content>
                
                <fo:flow flow-name="xsl-region-body">
                    <xsl:apply-templates select="/inzeraty/kategorie"/>
                    <xsl:apply-templates select="/inzeraty/inzerat"/>
                </fo:flow>
            </fo:page-sequence>
        </fo:root>
    </xsl:template>
    
    <!-- Kategorie Template -->
    <xsl:template match="kategorie">
        <fo:block font-size="12pt" font-weight="bold" space-before="10mm">
            <xsl:value-of select="nazev"/>
        </fo:block>
        <fo:block font-size="10pt" space-after="5mm">
            <xsl:value-of select="popis"/>
        </fo:block>
    </xsl:template>
    
    <!-- Inzerát Template -->
    <xsl:template match="inzerat">
        <fo:block space-before="5mm">
            <fo:table table-layout="fixed" width="100%">
                <fo:table-column column-width="proportional-column-width(1)"/>
                <fo:table-column column-width="proportional-column-width(3)"/>
                
                <fo:table-body>
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>ID</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block><xsl:value-of select="@id"/></fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Nadpis</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block><xsl:value-of select="nadpis"/></fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Popis</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block><xsl:value-of select="popis"/></fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Cena</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>
                                <xsl:choose>
                                    <xsl:when test="@typ = 'aukce'">
                                        <xsl:value-of select="aktualniCena"/>
                                    </xsl:when>
                                    <xsl:otherwise>
                                        <xsl:value-of select="cena"/>
                                    </xsl:otherwise>
                                </xsl:choose>
                            </fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Kategorie</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block><xsl:value-of select="kategorie"/></fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Prodávající</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>
                                <xsl:value-of select="prodavajici/jmeno"/> <xsl:value-of select="prodavajici/prijmeni"/><br/>
                                <xsl:value-of select="prodavajici/telefon"/><br/>
                                <xsl:value-of select="prodavajici/email"/><br/>
                                <xsl:value-of select="prodavajici/adresa/ulice"/> <xsl:value-of select="prodavajici/adresa/cisloPopisne"/>, 
                                <xsl:value-of select="prodavajici/adresa/mesto"/>, <xsl:value-of select="prodavajici/adresa/psc"/>
                            </fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Foto</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:external-graphic src="{foto}"/>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Datum Nahrání</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block><xsl:value-of select="datumNahrani"/></fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <fo:table-row>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block>Počet Zobrazení</fo:block>
                        </fo:table-cell>
                        <fo:table-cell padding="2mm" border="solid 1px black">
                            <fo:block><xsl:value-of select="pocetZobrazeni"/></fo:block>
                        </fo:table-cell>
                    </fo:table-row>
                    
                    <xsl:if test="@typ = 'aukce'">
                        <fo:table-row>
                            <fo:table-cell padding="2mm" border="solid 1px black">
                                <fo:block>Datum Konce</fo:block>
                            </fo:table-cell>
                            <fo:table-cell padding="2mm" border="solid 1px black">
                                <fo:block><xsl:value-of select="datumKonce"/></fo:block>
                            </fo:table-cell>
                        </fo:table-row>
                    </xsl:if>
                </fo:table-body>
            </fo:table>
        </fo:block>
    </xsl:template>
</xsl:stylesheet>